#ifndef WAR_HOURS_H
#define WAR_HOURS_H

#include "Classes.h"
#include <iostream>

struct WarHours {
    Kingdom* attacker;
    Kingdom* defender;
    
    int currentHour; //to count war hours sso o that in case both armies are on loop and reach 24 hours they get exhausted

    WarHours(Kingdom* atk, Kingdom* def) : attacker(atk), defender(def), currentHour(0) {}

    // Returns 1 if Attacker Routs (Defender wins), -1 if Defender Breaks (Attacker wins), 0 for Stalemate, 2 for Abort
    int resolveConflict();

    // Phase 5: Processes loot, relation resets, and global warmonger penalties
    void applyWarAftermath(Kingdom* attacker, Kingdom* defender, int result, int relations[10][10]);

private:
    // Takes a raw damage integer and cascades it through Cavalry -> Knight -> FootSoldier
    void applyCasualties(Kingdom* target, int incomingDamage);

    // Determines damage generated by a faction for the current phase
    int generateLineDamage(Kingdom* k, float strategyMod);

    // External snapshot function inspecting current Frontline structural health bounds
    int getFootSoldiersTotalHP(Kingdom* k);

    // Healing logic natively restores FootSoldier count
    int generateHealing(Kingdom* k, int incomingInfantryDamage);

    // Calculates a snapshot of a kingdom's total combat power
    int calculateTotalPower(Kingdom* k);

    int generateSiegeDamage(Kingdom* k, float strategyMod);

    // Parent damage function routing specifically to individual battle slices
    // Types: 1 = Siege, 2 = Flank, 3 = Elite, 4 = Line
    int generatePhaseDamage(Kingdom* k, float strategyMod, int phaseType);

    // Strategy multiplier: M = 1.0 + (CommandingLord.StrategyStat / 100.0)
    float getStrategyModifier(Kingdom* k);

    // Flat 10% daily attrition for WarShips
    void applyNavalAttrition(Kingdom* target);

    int generateFlankDamage(Kingdom* k, float strategyMod);
    int generateEliteDamage(Kingdom* k, float strategyMod);
};

#endif
